default:
    image: golang:1.18

stages:
    - build

build-api:
    stage: build
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - vendor/
    script:
        - mkdir -p ./bin/api
        - go mod download
        - go mod vendor
        - GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bin/api/api_amd64 ./services/api
    artifacts:
        name: api
        paths:
            - bin/api
        expose_as: api
        untracked: false
        expire_in: 7 days

build-ws:
    stage: build
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - vendor/
    script:
        - mkdir -p ./bin/ws
        - go mod download
        - go mod vendor
        - GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bin/ws/ws_amd64 ./services/ws
    artifacts:
        name: ws
        paths:
            - bin/ws
        expose_as: ws
        untracked: false
        expire_in: 7 days

build-discovery:
    stage: build
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - vendor/
    script:
        - mkdir -p ./bin/discovery
        - go mod download
        - go mod vendor
        - GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bin/discovery/discovery_amd64 ./services/discovery
    artifacts:
        name: discovery
        paths:
            - bin/discovery
        expose_as: discovery
        untracked: false
        expire_in: 7 days