version: "3.9"
services:
  api:
    image: registry.gitlab.com/george/shoya-go/api
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - SHOYA_CONFIG_JSON={"api":{"fiber":{"listen_address":"0.0.0.0:9000","proxy_header":"","prefork":false},"redis":{"host":"redis:6379","password":"","db":0},"postgres":{"host":"postgres","port":5432,"user":"shoya","password":"change_me","db":"shoya"},"apiConfigRefreshRateMs":10}}

  discovery:
    image: registry.gitlab.com/george/shoya-go/discovery
    restart: unless-stopped

  files:
    image: registry.gitlab.com/george/shoya-go/files
    restart: unless-stopped

  redis:
    image: redis/redis-stack-server
    restart: unless-stopped
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=shoya
      - POSTGRES_PASSWORD=change_me
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local